[package]
name = "base-x"
description = "Encode/decode any base"
version = "0.1.0"
authors = ["Alex R. <alexei.rudenko@gmail.com>"]
license = "MIT"
license-file = "LICENSE.md"
readme = "README.md"

[dev-dependencies]
rustc-serialize = "0.3"